name: Waka Readme

on:
  schedule:
    # Se ejecuta todos los días a las 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  update-readme:
    name: Update WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ░▒▓█
          TIME_RANGE: last_7_days
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
